version: '3'
services:
  gulp:
    build: .
    command: bash -c "gulp && gulp watch"
    volumes:
      - .:/app
      - /app/node_modules
  nginx:
    image: nginx
    volumes:
      - .:/usr/share/nginx/html
    ports:
      - 8080:80
