version: '3'
services:
  jekyll:
    build: .
    # command: jekyll build --watch # Without incremental allows better local dev troubleshooting
    command: jekyll build --watch --incremental --config _config.yml,_config_dev.yml
    image: clock_srly_io:latest
    volumes:
      - .:/usr/src/app:delegated
    environment:
      - JEKYLL_ENV=development
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./_site:/usr/share/nginx/html
    ports:
      - 3001:80
    depends_on:
      - jekyll
