version: '3'
services:
  jekyll:
    image: jekyll/jekyll
    command: jekyll build --watch --incremental
    volumes:
      - .:/srv/jekyll
  nginx:
    image: nginx
    volumes:
      - ./_site:/usr/share/nginx/html
    ports:
      - 8080:80
    depends_on:
      - jekyll
