version: '3'
services:
  jekyll:
    build: .
    command: jekyll build --watch --incremental
    environment:
      - JEKYLL_ENV=development
    volumes:
      - .:/srv/jekyll
    image: clock_srly_io:latest
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./_site:/usr/share/nginx/html
    ports:
      - 3001:80
    depends_on:
      - jekyll
