---
name: Deploy Stage

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn build
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          environment: stage
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }
          command: publish --env stage
